### ISSUE TITLE
[FE - Inspect page] Number of Page in "summary tree" and number of page in "inspect document"  shall be the same. "Page 1" is displayed in summary tree for Document where more then one page

### ISSUE THREAD

**Issue by nikitakovaliov92** [veraPDF/verapdf-webapp-gui#55] opened 2020-06-01 10:02 UTC
[Det is Berlin_rPDF_example_2017-02-27.pdf](https://github.com/veraPDF/verapdf-webapp-gui/files/4710851/Det.is.Berlin_rPDF_example_2017-02-27.pdf)
![page](https://user-images.githubusercontent.com/59257413/83399094-46efc100-a409-11ea-9326-a76159d0d9d6.png)

**Comment by yuliya-ivaniukovich** [comment] 2020-06-03 11:41
Duplicate of https://github.com/veraPDF/verapdf-webapp-gui/issues/67

**Closed by yuliya-ivaniukovich** 2020-06-03 11:41 UTC
Labels: duplicate
