### ISSUE TITLE
[FE] - Failed to execute 'transaction': The database connection is closing

### ISSUE THREAD

**Issue by nikitakovaliov92** [veraPDF/verapdf-webapp-gui#82] opened 2020-06-08 16:37 UTC
![img](https://user-images.githubusercontent.com/59257413/84056953-a2005580-a9bf-11ea-92ce-aea3999dada8.png)

Possible steps to reproduce (**i'm not sure**):

1. Execute job and click to logo from summary page

**Actual result:** DOMException is present

**Comment by yuliya-ivaniukovich** [comment] 2020-06-08 17:31
Looks like concurrency issue, as if we're trying to access database while page reload is started. We need to make sure to await for DB operations to be complete (maybe even close the connection manually) before reloading the page. All operations should handle potential closing in the middle not to block the page.

**Comment by bdoubrov** [comment] 2023-05-17 08:20
Can not reproduce in the latest version

**Closed by bdoubrov** 2023-05-17 08:20 UTC
